### ISSUE TITLE
Scrolling does not work

### ISSUE THREAD

**Issue by matthias3333** [Don-Cryptus/coding.global-web#6]
How can I scroll on this page?

![image](https://user-images.githubusercontent.com/3605191/224849601-3978f0fc-c193-494f-9bdf-f486a7da730a.png)

@Bit-Barron @superriot Can you fix it?

**Comment by Don-Cryptus** [comment]
@Bit-Barron pls do

**Comment by matthias3333** [comment]
Fixed in #10
